title: "Baran Saghafi CV"
description: "Urban Planning and Management Researcher"
contact: emailS: "baransaghafiii@gmail.com · baransaghafi@ut.ac.ir" "LinkedIn: (https://www.linkedin.com/in/baran-saghafi-3a6306245/)"  
📱 [+98 910 911 7523](tel:+989109117523) 
theme: jekyll-theme-minimal
logo: baran.jpg
