title: "Baran Saghafi CV"
description: "Urban Planning and Management Researcher"
contact: "emailS: baransaghafiii@gmail.com · baransaghafi@ut.ac.ir" "LinkedIn: (https://www.linkedin.com/in/baran-saghafi-3a6306245/)"  "phone: (tel:+989109117523)" 
theme: jekyll-theme-minimal
logo: baran.jpg
