title: "Baran Saghafi CV"
description: "Urban Planning Researcher and GIS, Spatial & Data Analysis"
email: "baransaghafiii@gmail.com"
phone: "+98 912 711 7523"
theme: jekyll-theme-minimal
logo: cv.photo.png

