title: "Baran Saghafi CV"
description: "Urban Planning and Management Researcher"
theme: jekyll-theme-minimal
logo: Baran.jpg
email: "baransaghafiii@gmail.com"
phone: "+98 912 345 6789"
social:
  github: "https://github.com/baransaghafi"
  linkedin: "https://www.linkedin.com/in/baransaghafi/"
